name: example-environment
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.7
  - pytorch=1.10.0
  - torchvision=0.11.0
  - torchaudio=0.10.0
  - cudatoolkit=11.3
  - pip
  - pip:
    - numpy
    - pandas
    - matplotlib